# serverless.yml

service: ems-dinghies

useDotenv: true

package:
    individually: true

plugins:
    - serverless-webpack
    - serverless-offline

custom:
    webpack:
        webpackConfig: ./webpack_lambda.config.js
        includeModules: true
    serverless-offline:
        noPrependStageInUrl: true

provider:
    name: aws
    runtime: nodejs12.x
    stage: ${opt:stage, "dev"}
    apiGateway:
        shouldStartNameWithService: true
    endpointType: REGIONAL
    region: eu-west-2
    lambdaHashingVersion: 20201221
    iamRoleStatements:
        - Effect: Allow
          Action:
              - lambda:InvokeFunction
          Resource: '*'

functions:
    staticApp:
        memorySize: 512
        handler: src/servers/static.handler
        events:
            - http: ANY /
            - http: ANY /{proxy+}
